<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="FluentAssertions" Version="8.10.0" />
	  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
	  <PackageReference Include="MSTest.TestAdapter" Version="3.6.1" />
	  <PackageReference Include="MSTest.TestFramework" Version="3.6.1" />
	  <PackageReference Include="NSubstitute" Version="6.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CleanTeeth.Application\CleanTeeth.Application.csproj" />
    <ProjectReference Include="..\CleanTeeth.Domain\CleanTeeth.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
